# Generated by Django 5.1.2 on 2024-11-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_administrador_categorias_detalles_orden_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono',
            new_name='telefono_usuario',
        ),
    ]
