# Generated by Django 5.1.2 on 2024-10-29 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_administrador_categorias_detalles_orden_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Postre', models.CharField(max_length=20)),
                ('Plato_Fuerte', models.CharField(max_length=80)),
                ('Bebida', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='Bebida',
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='Entrada',
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='Plato_Fuerte',
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='Postre',
        ),
        migrations.AddField(
            model_name='categorias',
            name='Nombre_Categoria',
            field=models.CharField(default='Sin Categoría', max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Plato_Del_Dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menu_dia'),
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
    ]
