# Generated by Django 5.1.2 on 2024-11-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_telefono_usuario_telefono_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono_usuario',
        ),
    ]
